/*
 * English catalogue for the dashboard chrome.
 *
 * Woordenlijst / glossary:
 *   Leerpret, Leerbox, Leerpretpark  -> product names, not translated
 *   leerobject      -> learning object
 *   weerstandsobject-> resistance object
 *   gevatte leerbox -> captured Leerbox
 *   route           -> route
 *   controle/audit  -> check / audit
 *
 * Een lege waarde valt automatisch terug op de Nederlandse tekst uit nl.js.
 */

export const messages = {
  "status.activePage": "Active page",
  "status.activeRole": "Active role",
  "status.connecting": "Connecting...",
  "workbench.view": "Workbench view",
  "workbench.description": "Description",
  "workbench.edit": "Edit",
  "workbench.edit.title": "Edit the Leerbox",
  "workbench.preview": "Preview",
  "workbench.preview.title": "Open the preview",
  "dock.title": "Dashboard menu",
  "dock.role": "Role perspective",
  "dock.role.aria": "Choose role perspective",
  "dock.menu": "Menu",
  "dock.menu.aria": "Choose a section",
  "dock.workbenches": "Workbenches",
  "role.attraction": "Learning attraction",
  "role.learner": "Learner",
  "role.guest": "Guest",
  "auth.login": "Log in",
  "auth.logout": "Log out",
  "menu.sections": "Editor sections",
  "menu.collapse": "Collapse",
  "menu.collapse.aria": "Collapse the left tool panel",
  "menu.back": "← Back to Leerbox",
  "menu.activeLeerbox": "Active Leerbox",
  "menu.loading": "Loading...",
  "menu.description": "View description",
  "menu.progress": "Leerbox progress",
  "menu.commandCentre": "Command centre",
  "cluster.oa": "Educational architecture",
  "cluster.oa.title": "Educational architecture: what the learning attraction calls for — the organisation of learning",
  "cluster.build": "Build commands",
  "cluster.objectTypes": "Object types",
  "advisor.open": "Open the advisor",
  "advisor.collapse.aria": "Collapse the advisor",
  "advisor.title": "Advisor",
  "advisor.heading": "Build advice",
  "advisor.intro": "Design advice without leaving the Leerbox map.",
  "advisor.scanLabel": "Scan",
  "advisor.scanHint": "First check whether start, success and route are logically connected.",
  "advisor.actions": "Advisor functions",
  "advisor.chat": "Chat with the agent",
  "advisor.scan": "Scan the route",
  "advisor.advice": "Ask for advice",
  "advisor.warnings": "Warnings",
  "advisor.footnote": "The advisor stays beside the tools",
  "cluster.objectTypes.title": "Learning object: choose the type you add",
  "cluster.tools": "Tools",
  "cluster.tools.title": "Tools: add objects, steps and conditions",
  "cluster.beheer": "Manage",
  "cluster.beheer.title": "Manage: create a Leerbox and feed it with sources",
  "cluster.analyse": "Analyse",
  "cluster.analyse.title": "Analyse: review, check and account for the captured Leerbox",
  "nav.home": "Home",
  "nav.park": "Leerpretpark",
  "nav.article": "Article",
  "nav.learningbox": "Leerbox",
  "nav.editor": "Editor",
  "nav.preview": "Preview",
  "nav.engine": "Engine",
  "nav.snnInnovationTest": "SNN Innovation Test",
  "nav.data": "Data",
  "nav.service": "Service",
  "nav.help": "Help",
  "settings.title": "Settings",
  "settings.language": "Language",
  "settings.service": "Service",
  "settings.access": "Access",
  "settings.privacy": "Privacy & data",
  "hud.bronnen": "Sources",
  "hud.bronnen.title": "Import and download sources",
  "hud.code": "Code",
  "hud.code.title": "Computer-language statements",
  "hud.controle": "Check",
  "hud.controle.title": "Check and audit",
  "hud.doelen": "Goals",
  "hud.doelen.title": "Goals: learning objectives and objective hierarchy",
  "hud.game": "Game",
  "hud.game.title": "Game: rules and room to play",
  "hud.info": "Info",
  "hud.info.title": "Info box: Leerbox type and social setting",
  "hud.meten": "Measure",
  "hud.meten.title": "Sensors and Leerpret measurement",
  "hud.missie": "Mission",
  "hud.missie.title": "Mission",
  "hud.nieuw": "New",
  "hud.nieuw.title": "New Leerbox",
  "hud.normaal": "Standard",
  "hud.normaal.title": "Standard learning object",
  "hud.object": "Object",
  "hud.object.title": "New object",
  "hud.plan": "Plan",
  "hud.plan.title": "Design plan",
  "hud.preview": "Preview",
  "hud.preview.title": "Generate preview",
  "hud.rapport": "Report",
  "hud.rapport.title": "Captured Leerbox as a report",
  "hud.route": "Route",
  "hud.route.title": "Route and sequence",
  "hud.stap": "Step",
  "hud.stap.title": "New route step",
  "hud.start": "Start",
  "hud.start.title": "Start: onboarding and first action",
  "hud.strategie": "Strategy",
  "hud.strategie.title": "Strategy: approach and design",
  "hud.structuur": "Structure",
  "hud.structuur.title": "Learning architecture",
  "hud.succes": "Success",
  "hud.succes.title": "Success: the definition of success",
  "hud.visie": "Vision",
  "hud.visie.title": "Vision: desired situation and educational principles",
  "hud.voorw": "Cond.",
  "hud.voorw.title": "New condition",
  "hud.weerstand": "Resistance",
  "hud.weerstand.title": "Resistance: the main barrier",
  "preset.entry": "Start",
  "preset.entry.title": "Start object",
  "preset.normal": "Standard",
  "preset.normal.title": "Standard learning object",
  "preset.resistance": "Resistance",
  "preset.resistance.title": "Resistance object",
  "preset.success": "Success",
  "preset.success.title": "Success object",
};
