/*
 * Catálogo en español para la interfaz del panel.
 *
 * Woordenlijst / glosario:
 *   Leerpret, Leerbox, Leerpretpark  -> nombres de producto, sin traducir
 *   leerobject      -> objeto de aprendizaje
 *   weerstandsobject-> objeto de resistencia
 *   gevatte leerbox -> Leerbox capturada
 *   route           -> ruta
 *   controle/audit  -> control / auditoría
 *
 * Een lege waarde valt automatisch terug op de Nederlandse tekst uit nl.js.
 */

export const messages = {
  "status.activePage": "Página activa",
  "status.activeRole": "Rol activo",
  "status.connecting": "Conectando...",
  "workbench.view": "Vista del banco de trabajo",
  "workbench.description": "Descripción",
  "workbench.edit": "Editar",
  "workbench.edit.title": "Editar la Leerbox",
  "workbench.preview": "Vista previa",
  "workbench.preview.title": "Abrir la vista previa",
  "dock.title": "Menú del panel",
  "dock.role": "Perspectiva de rol",
  "dock.role.aria": "Elegir perspectiva de rol",
  "dock.menu": "Menú",
  "dock.menu.aria": "Elegir sección",
  "dock.workbenches": "Bancos de trabajo",
  "role.attraction": "Atracción de aprendizaje",
  "role.learner": "Aprendiz",
  "role.guest": "Invitado",
  "auth.login": "Iniciar sesión",
  "auth.logout": "Cerrar sesión",
  "menu.sections": "Secciones del editor",
  "menu.collapse": "Contraer",
  "menu.collapse.aria": "Contraer el panel de herramientas izquierdo",
  "menu.back": "← Volver a la Leerbox",
  "menu.activeLeerbox": "Leerbox activa",
  "menu.loading": "Cargando...",
  "menu.description": "Ver la descripción",
  "menu.progress": "Progreso de la Leerbox",
  "menu.commandCentre": "Centro de mando",
  "cluster.oa": "Arquitectura educativa",
  "cluster.oa.title": "Arquitectura educativa: lo que pide la atracción de aprendizaje — la organización del aprendizaje",
  "cluster.build": "Comandos de construcción",
  "cluster.objectTypes": "Tipos de objeto",
  "advisor.open": "Abrir el asesor",
  "advisor.collapse.aria": "Contraer el asesor",
  "advisor.title": "Asesor",
  "advisor.heading": "Consejo de construcción",
  "advisor.intro": "Consejo de diseño sin salir del mapa de la Leerbox.",
  "advisor.scanLabel": "Escaneo",
  "advisor.scanHint": "Comprueba primero si el inicio, el éxito y la ruta están conectados con lógica.",
  "advisor.actions": "Funciones del asesor",
  "advisor.chat": "Chatear con el agente",
  "advisor.scan": "Escanear la ruta",
  "advisor.advice": "Pedir consejo",
  "advisor.warnings": "Advertencias",
  "advisor.footnote": "El asesor permanece junto a las herramientas",
  "cluster.objectTypes.title": "Objeto de aprendizaje: elige el tipo que añades",
  "cluster.tools": "Herramientas",
  "cluster.tools.title": "Herramientas: añadir objetos, pasos y condiciones",
  "cluster.beheer": "Gestión",
  "cluster.beheer.title": "Gestión: crear una Leerbox y alimentarla con fuentes",
  "cluster.analyse": "Análisis",
  "cluster.analyse.title": "Análisis: revisar, controlar y justificar la Leerbox capturada",
  "nav.home": "Inicio",
  "nav.park": "Leerpretpark",
  "nav.article": "Artículo",
  "nav.learningbox": "Leerbox",
  "nav.editor": "Editor",
  "nav.preview": "Vista previa",
  "nav.engine": "Motor",
  "nav.snnInnovationTest": "Prueba de innovación SNN",
  "nav.data": "Datos",
  "nav.service": "Servicio",
  "nav.help": "Ayuda",
  "settings.title": "Ajustes",
  "settings.language": "Idioma",
  "settings.service": "Servicio",
  "settings.access": "Acceso",
  "settings.privacy": "Privacidad y datos",
  "hud.bronnen": "Fuentes",
  "hud.bronnen.title": "Importar y descargar fuentes",
  "hud.code": "Código",
  "hud.code.title": "Sentencias en lenguaje de máquina",
  "hud.controle": "Control",
  "hud.controle.title": "Control y auditoría",
  "hud.doelen": "Objetivos",
  "hud.doelen.title": "Objetivos: objetivos de aprendizaje y su jerarquía",
  "hud.game": "Juego",
  "hud.game.title": "Juego: reglas y margen de juego",
  "hud.info": "Info",
  "hud.info.title": "Ficha informativa: tipo de Leerbox y entorno social",
  "hud.meten": "Medición",
  "hud.meten.title": "Sensores y medición Leerpret",
  "hud.missie": "Misión",
  "hud.missie.title": "Misión",
  "hud.nieuw": "Nueva",
  "hud.nieuw.title": "Nueva Leerbox",
  "hud.normaal": "Estándar",
  "hud.normaal.title": "Objeto de aprendizaje estándar",
  "hud.object": "Objeto",
  "hud.object.title": "Nuevo objeto",
  "hud.plan": "Plan",
  "hud.plan.title": "Plan de diseño",
  "hud.preview": "Vista previa",
  "hud.preview.title": "Generar vista previa",
  "hud.rapport": "Informe",
  "hud.rapport.title": "La Leerbox capturada como informe",
  "hud.route": "Ruta",
  "hud.route.title": "Ruta y secuencia",
  "hud.stap": "Paso",
  "hud.stap.title": "Nuevo paso de ruta",
  "hud.start": "Inicio",
  "hud.start.title": "Inicio: incorporación y primera acción",
  "hud.strategie": "Estrategia",
  "hud.strategie.title": "Estrategia: enfoque y diseño",
  "hud.structuur": "Estructura",
  "hud.structuur.title": "Arquitectura de aprendizaje",
  "hud.succes": "Éxito",
  "hud.succes.title": "Éxito: la definición de éxito",
  "hud.visie": "Visión",
  "hud.visie.title": "Visión: situación deseada y principios pedagógicos",
  "hud.voorw": "Cond.",
  "hud.voorw.title": "Nueva condición",
  "hud.weerstand": "Resistencia",
  "hud.weerstand.title": "Resistencia: la barrera principal",
  "preset.entry": "Inicio",
  "preset.entry.title": "Objeto inicial",
  "preset.normal": "Estándar",
  "preset.normal.title": "Objeto de aprendizaje estándar",
  "preset.resistance": "Resistencia",
  "preset.resistance.title": "Objeto de resistencia",
  "preset.success": "Éxito",
  "preset.success.title": "Objeto de éxito",
};
