/*
 * Nederlandse brontekst voor het dashboard-chrome.
 * Dit is de referentiecatalogus: elke sleutel hier hoort ook in en.js, es.js en de.js.
 */

export const messages = {
  "status.activePage": "Actieve pagina",
  "status.activeRole": "Actieve rol",
  "status.connecting": "Verbinding maken...",
  "workbench.view": "Werkbank weergave",
  "workbench.description": "Beschrijving",
  "workbench.edit": "Bewerken",
  "workbench.edit.title": "Leerbox bewerken",
  "workbench.preview": "Preview",
  "workbench.preview.title": "Preview openen",
  "dock.title": "Dashboardmenu",
  "dock.role": "Rolperspectief",
  "dock.role.aria": "Kies rolperspectief",
  "dock.menu": "Menu",
  "dock.menu.aria": "Kies onderdeel",
  "dock.workbenches": "Werkbanken",
  "role.attraction": "Leerattractie",
  "role.learner": "Lerende",
  "role.guest": "Gast",
  "auth.login": "Login",
  "auth.logout": "Logout",
  "menu.sections": "Editoronderdelen",
  "menu.collapse": "Inklappen",
  "menu.collapse.aria": "Linker gereedschapspaneel inklappen",
  "menu.back": "← Terug naar Leerbox",
  "menu.activeLeerbox": "Actieve leerbox",
  "menu.loading": "Laden...",
  "menu.description": "Beschrijving bekijken",
  "menu.progress": "Voortgang leerbox",
  "menu.commandCentre": "Commandocentrum",
  "cluster.oa": "Onderwijsarchitectuur",
  "cluster.oa.title": "Onderwijsarchitectuur: wat de leerattractie wenst — de organisatie van het leren",
  "cluster.build": "Bouwcommando's",
  "cluster.objectTypes": "Objecttypes",
  "advisor.open": "Adviseur openen",
  "advisor.collapse.aria": "Adviseur inklappen",
  "advisor.title": "Adviseur",
  "advisor.heading": "Bouwadvies",
  "advisor.intro": "Ontwerpadvies zonder de leerboxkaart te verlaten.",
  "advisor.scanLabel": "Scan",
  "advisor.scanHint": "Controleer eerst of start, succes en route logisch verbonden zijn.",
  "advisor.actions": "Adviseurfuncties",
  "advisor.chat": "Chat met de agent",
  "advisor.scan": "Scan de route",
  "advisor.advice": "Vraag advies",
  "advisor.warnings": "Waarschuwingen",
  "advisor.footnote": "Adviseur blijft naast het gereedschap",
  "cluster.objectTypes.title": "Leerobject: kies het type dat je toevoegt",
  "cluster.tools": "Gereedschap",
  "cluster.tools.title": "Gereedschap: objecten, stappen en voorwaarden toevoegen",
  "cluster.beheer": "Beheer",
  "cluster.beheer.title": "Beheer: een leerbox aanmaken en van bronnen voorzien",
  "cluster.analyse": "Analyse",
  "cluster.analyse.title": "Analyse: de gevatte leerbox bekijken, controleren en verantwoorden",
  "nav.home": "Home",
  "nav.park": "Leerpretpark",
  "nav.article": "Artikel",
  "nav.learningbox": "Leerbox",
  "nav.editor": "Editor",
  "nav.preview": "Preview",
  "nav.engine": "Engine",
  "nav.snnInnovationTest": "SNN Innovatietest",
  "nav.data": "Data",
  "nav.service": "Service",
  "nav.help": "Help",
  "settings.title": "Instellingen",
  "settings.language": "Taal",
  "settings.service": "Service",
  "settings.access": "Toegang",
  "settings.privacy": "Privacy & data",
  "hud.bronnen": "Bronnen",
  "hud.bronnen.title": "Bronnen importeren en downloaden",
  "hud.code": "Code",
  "hud.code.title": "Computertaal-statements",
  "hud.controle": "Controle",
  "hud.controle.title": "Controle en audit",
  "hud.doelen": "Doelen",
  "hud.doelen.title": "Doelen: leerdoelen en leerdoelhiërarchie",
  "hud.game": "Game",
  "hud.game.title": "Game: spelregels en speelruimte",
  "hud.info": "Info",
  "hud.info.title": "Infobox: type Leerbox en sociale setting",
  "hud.meten": "Meten",
  "hud.meten.title": "Sensoren en Leerpret-meting",
  "hud.missie": "Missie",
  "hud.missie.title": "Missie",
  "hud.nieuw": "Nieuw",
  "hud.nieuw.title": "Nieuwe leerbox",
  "hud.normaal": "Normaal",
  "hud.normaal.title": "Normaal leerobject",
  "hud.object": "Object",
  "hud.object.title": "Nieuw object",
  "hud.plan": "Plan",
  "hud.plan.title": "Ontwerpplan",
  "hud.preview": "Preview",
  "hud.preview.title": "Preview genereren",
  "hud.rapport": "Rapport",
  "hud.rapport.title": "Gevatte leerbox als rapport",
  "hud.route": "Route",
  "hud.route.title": "Route en volgorde",
  "hud.stap": "Stap",
  "hud.stap.title": "Nieuwe routestap",
  "hud.start": "Start",
  "hud.start.title": "Start: onboarding en eerste actie",
  "hud.strategie": "Strategie",
  "hud.strategie.title": "Strategie: aanpak en ontwerp",
  "hud.structuur": "Structuur",
  "hud.structuur.title": "Leerarchitectuur",
  "hud.succes": "Succes",
  "hud.succes.title": "Succes: de succesdefinitie",
  "hud.visie": "Visie",
  "hud.visie.title": "Visie: gewenste situatie en onderwijskundige opvattingen",
  "hud.voorw": "Voorw.",
  "hud.voorw.title": "Nieuwe voorwaarde",
  "hud.weerstand": "Weerstand",
  "hud.weerstand.title": "Weerstand: de belangrijkste barrière",
  "preset.entry": "Start",
  "preset.entry.title": "Startobject",
  "preset.normal": "Normaal",
  "preset.normal.title": "Normaal leerobject",
  "preset.resistance": "Weerstand",
  "preset.resistance.title": "Weerstandsobject",
  "preset.success": "Succes",
  "preset.success.title": "Succesobject",
};
